blank_issues_enabled: false
contact_links:
    - name: Ask a Question and installation issues
      url: https://github.com/chiribuc/vue-stack-grid/discussions/new?category=q-a
      about: Ask the community for help
    - name: Feature Request
      url: https://github.com/chiribuc/vue-stack-grid/discussions/new?category=ideas
      about: Share ideas for new features
    - name: Bug Report
      url: https://github.com/chiribuc/vue-stack-grid/issues/new
      about: Report a reproducable bug
